---
- name: Collect and Send File Information to Nexus Artifactory
  hosts: all
  gather_facts: no
  tasks:

    - name: Get file details
      stat:
        path: "/path/to/file"  # Change this to the actual file path
      register: file_info

    - name: Store file details in a variable
      set_fact:
        file_data: 
          hostname: "{{ inventory_hostname }}"
          path: "/path/to/file"
          exists: "{{ file_info.stat.exists }}"
          size: "{{ file_info.stat.size | default('N/A') }}"
          permissions: "{{ file_info.stat.mode | default('N/A') }}"
          last_modified: "{{ file_info.stat.mtime | default('N/A') }}"

- name: Consolidate and Send Data to Nexus Artifactory
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Merge collected data from all servers
      set_fact:
        all_files_info: "{{ hostvars.values() | map(attribute='file_data') | list }}"

    - name: Generate CSV content dynamically
      set_fact:
        csv_content: |
          hostname,path,exists,size,permissions,last_modified
          {% for item in all_files_info %}
          {{ item.hostname }},{{ item.path }},{{ item.exists }},{{ item.size }},{{ item.permissions }},{{ item.last_modified }}
          {% endfor %}

    - name: Post CSV data directly to Nexus Artifactory
      command: >
        curl -X PUT -u nexus_user:nexus_password
        -H "Content-Type: text/csv"
        --data-binary @- "http://nexus.example.com/repository/raw-repo/file_info.csv"
      args:
        stdin: "{{ csv_content | trim }}"
      register: curl_response

    - name: Print Nexus API Response
      debug:
        var: curl_response.stdout
